# Generated by Django 4.0.3 on 2022-03-06 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Короткое наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('version', models.CharField(max_length=5, verbose_name='Версия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала действия справочника этой версии')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ReferenceBookElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Код элемента')),
                ('value', models.CharField(max_length=10, verbose_name='Значение')),
                ('reference_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='app.referencebook')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочников',
            },
        ),
    ]
